<h1>The catchError operator takes as input an Observable that might error out, and starts emitting the values of the input Observable in its output Observable.</h1>
<h3>signature: catchError(project : function): Observable</h3>
<h3>Gracefully handle errors in an observable sequence.</h3>
<div><img src="https://www.bitovi.com/hs-fs/hubfs/catcherror1.png?width=694&height=224&name=catcherror1.png" alt=""></div>
<button (click)="catcherrormethod()">catcherror</button>
